name: Build Obsidian Plugin

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build plugin
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: obsidian-plugin
        path: |
          my-obsidian-plugin/main.js
          my-obsidian-plugin/manifest.json
          my-obsidian-plugin/styles.css # If you have a styles.css file
